.PHONY: all test lint-dockerfiles lint-scripts validate-json clean

all: test

test:
	./run-all.sh

lint-dockerfiles:
	../lint-dockerfiles.sh

lint-scripts:
	../lint-scripts.sh

validate-json:
	../validate-json.sh

clean:
	@echo "Nothing to clean"